### ISSUE TITLE
无法正常启动,日志如下

### ISSUE THREAD

**Issue by HP-Li** [esrrhs/docker-thunder-xware#5]
stderr: ./start.sh: line 5: ./portal: cannot execute binary file: Exec format error

**Comment by esrrhs** [comment]
@HP-Li 你的平台不是x86

**Comment by HP-Li** [comment]
> @HP-Li 你的平台不是x86

我的平台是x86的啊, i3-3220的openwrt

**Comment by esrrhs** [comment]
@HP-Li openwrt不清楚 可能是缺一些库，这个迅雷的不好用了，直接有aria2把
